[package]
name = "snake"
version = "0.1.0"
edition = "2018"
authors = ["Sarah N. Ryan <phoeniixz@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.7"
